### ISSUE TITLE
ClassNotFoundException: 

### ISSUE THREAD

**Issue by zhengwanzhang** [alipay/sofa-boot#208]
报错提示：
`Caused by: java.lang.NoClassDefFoundError: com/iwallet/biz/common/util/UniqID
	at com.alipay.common.event.impl.DefaultUniformEventBuilder.<init>(DefaultUniformEventBuilder.java:19)
	at com.hundsun.gold.mq.MqService.<init>(MqService.java:20)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 30 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.iwallet.biz.common.util.UniqID
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 common frames omitted`
错误模块com.alipay.system:alipay-system-event:3.1.17，类com.alipay.common.event.impl.DefaultUniformEventBuilder，是在运行官网上的关于消息队列的代码时抛出的异常，希望上面的信息对你们定位错误有帮助

**Comment by QilongZhang** [comment]
@zhengwanzhang  麻烦告知是官网那个用例？ 是这个 https://www.cloud.alipay.com/docs/2/56528 吗？

**Comment by zhengwanzhang** [comment]
@QilongZhang  是快速开始的示例https://www.cloud.alipay.com/docs/2/56198

**Comment by QilongZhang** [comment]
@zhengwanzhang  添加这个
```xml
<groupId>com.alipay.common</groupId>
<artifactId>alipay-common-lang</artifactId>
```
你的是商业版，这个包没有开源
