### ISSUE TITLE
关于ark-plugin包的类加载不到的问题

### ISSUE THREAD

**Issue by luoluo001** [alipay/sofa-boot#240]
background : project ,springboot    dev tool,IDEA

     i can't load class of ark-plugin's jars when visit web api.(当访问web接口，不能加载到ark-plugin jar包的class)
the exception:
com.alipay.sofa.ark.exception.ArkLoaderException: [ArkBiz Loader] Startup In IDE:Mock version : can not load class: com.dinfo.custom.comp.AppServer
	at com.alipay.sofa.ark.container.service.classloader.BizClassLoader.loadClassInternal(BizClassLoader.java:90)
	at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassloader.loadClass(AbstractClasspathClassloader.java:59)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.dinfo.model.ModuleInvocation.invoke(ModuleInvocation.java:32)
	at com.dinfo.controller.CompController.httpLocalExecute(CompController.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

the code:
 Class<?> cls = Class.forName(className);(在接口Controller中执行该代码报错)

根据看的源码部分发现：每个pligin都有各自对应的类加载器，在PluginManagerServiceImpl中有个plugins map是可以获取plugin 问题是 ContainerClassLoader 我不知道怎么获取到，请问有获取的方法吗？或者 有什么方法可以直接获取到ark-plugin中的class？

**Comment by QilongZhang** [comment]
如果 ark plugin 将对应的类导出，你直接 Class.forName() 即可获取。 另能否上传提供的报错Demo？

**Comment by luoluo001** [comment]
> 如果 ark plugin 将对应的类导出，你直接 Class.forName() 即可获取。 另能否上传提供的报错Demo？

谢谢您，github地址为 https://github.com/luoluo001/sofaarkdemo  设置了导出类但是没有看到效果。另外也不是很理解配置导出类，按文档的介绍，导出类不是其他ark-plugin加载的时候会优先加载该导出类的这个类吗，可是springboot这个ark jar不属于ark-plugin啊？

**Comment by QilongZhang** [comment]
> github地址为 https://github.com/luoluo001/sofaarkdemo 设置了导出类但是没有看到效果。

postman 测试参数设置错误，你在配置导出类是 `myproject.custom.comp.AppServer`，然则参数设置的是 `com.dinfo.custom.comp.AppServer`。

> 另外也不是很理解配置导出类，按文档的介绍，导出类不是其他ark-plugin加载的时候会优先加载该导出类的这个类吗，可是springboot这个ark jar不属于ark-plugin啊？

插件导出类优先被其他ark-plugin加载，前提是其他插件配置了**导入类**。 springboot 工程中之所以能够加载到ark plugin的导出类，因为biz会默认优先加载所有ark plugin 的导出类，不需要配置类似的导入类。 参考文档 http://www.sofastack.tech/sofa-boot/docs/sofa-ark-classloader

**Comment by luoluo001** [comment]
> > github地址为 https://github.com/luoluo001/sofaarkdemo 设置了导出类但是没有看到效果。
> 
> postman 测试参数设置错误，你在配置导出类是 `myproject.custom.comp.AppServer`，然则参数设置的是 `com.dinfo.custom.comp.AppServer`。
> 
> > 另外也不是很理解配置导出类，按文档的介绍，导出类不是其他ark-plugin加载的时候会优先加载该导出类的这个类吗，可是springboot这个ark jar不属于ark-plugin啊？
> 
> 插件导出类优先被其他ark-plugin加载，前提是其他插件配置了**导入类**。 springboot 工程中之所以能够加载到ark plugin的导出类，因为biz会默认优先加载所有ark plugin 的导出类，不需要配置类似的导入类。 参考文档 http://www.sofastack.tech/sofa-boot/docs/sofa-ark-classloader
给大佬添麻烦了，项目改了 包名忘记改过来了，不好意思
