### ISSUE TITLE
SofaBootstrapRunListener failed to fetch application configuration

### ISSUE THREAD

**Issue by ankeway** [alipay/sofa-boot#371]
use Srping Boot 2.1.2 , At the time of application startup prompt fault as follows

java.lang.ClassCastException: org.springframework.core.env.SimpleCommandLinePropertySource cannot be cast to org.springframework.core.env.MapPropertySource
	at com.alipay.sofa.infra.listener.SofaBootstrapRunListener.lambda$assemblyLogSetting$1(SofaBootstrapRunListener.java:62) ~[infra-sofa-boot-starter-3.1.1.jar:3.1.1]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_181]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_181]
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.forEachRemaining(CopyOnWriteArrayList.java:1206) ~[?:1.8.0_181]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_181]

**Comment by QilongZhang** [comment]
感谢反馈，我们将于 3.1.3 修复这个问题。 2.x 版本中没有这个问题。
