### ISSUE TITLE
SofaRuntimeSpringContextInitializer 在 Spring Cloud 环境下多次初始化报错

### ISSUE THREAD

**Issue by glmapper** [alipay/sofa-boot#378]
版本：SOFABoot 3.1.0 版本 +  SpringCloud G 

异常堆栈：

```java
java.lang.IllegalStateException: Could not register object [com.alipay.sofa.runtime.service.impl.BindingConverterFactoryImpl@63a5d002] under bean name 'bindingConverterFactory': there is already object [com.alipay.sofa.runtime.service.impl.BindingConverterFactoryImpl@63a5d002] bound
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.registerSingleton(DefaultSingletonBeanRegistry.java:120)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerSingleton(DefaultListableBeanFactory.java:1027)
	at com.alipay.sofa.runtime.spring.listener.SofaRuntimeApplicationListener.initApplicationContext(SofaRuntimeApplicationListener.java:74)
	at com.alipay.sofa.runtime.spring.listener.SofaRuntimeApplicationListener.onApplicationEvent(SofaRuntimeApplicationListener.java:114)
	at com.alipay.sofa.runtime.spring.listener.SofaRuntimeApplicationListener.onApplicationEvent(SofaRuntimeApplicationListener.java:60)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
	at org.springframework.cloud.context.restart.RestartListener.onApplicationEvent(RestartListener.java:68)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:191)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:105)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:71)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at io.sofastack.cloud.trade.TradingApplication.main(TradingApplication.java:13)

Process finished with exit code 1

```

**Comment by QilongZhang** [comment]
SOFABoot 2.6.0 和 SOFABoot 3.1.0 引入的问题，需要在 SofaRuntimeSpringContextInitializer 判断 Spring Cloud 环境再做初始化

**Comment by QilongZhang** [comment]
刚 Review 了代码，该问题在 3.1.3 已经修复了，引入 3.1.3 版本即可。
