### ISSUE TITLE
sofaboot构建，ApplicationEnvironmentPreparedListener ClassNotFoundException

### ISSUE THREAD

**Issue by leyou240** [alipay/sofa-boot#381]
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationListener : com.alipay.sofa.rpc.boot.context.ApplicationEnvironmentPreparedListener
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:450)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:429)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:420)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:270)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:249)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at cn.esstx.ProviderApplication.main(ProviderApplication.java:13)
Caused by: java.lang.ClassNotFoundException: com.alipay.sofa.rpc.boot.context.ApplicationEnvironmentPreparedListener

其中pom引用如下：
 <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>rpc-sofa-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>runtime-sofa-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>isle-sofa-boot-starter</artifactId>
        </dependency>

**Comment by leyou240** [comment]
之前看过源码，删除本地maven仓库重新构建就可以了
